baseURL = 'https://eidasmonitor.eu/'
languageCode = 'en-US'
title = 'eIDAS Monitor'

[params] 
  newsletterURL = "https://secure.dialog-mail.com/s/6U6yH"

[params.footer]
  owner = "epicenter.works"
  ownerURL = "https://epicenter.works/en/"
  imprintURL = 'https://epicenter.works/en/contact'
  privacyURL = 'https://epicenter.works/en/privacy'

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
  [[module.imports]]
    path = 'github.com/hugomods/icons/vendors/tabler'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.mounts]]
    source = 'node_modules/@fontsource/anton/files'
    target = 'static/fonts'
    includeFiles = '*-latin-*'
  [[module.mounts]]
    source = 'node_modules/@fontsource/poppins/files'
    target = 'static/fonts'
    includeFiles = '*-latin-600-normal-*'
  [[module.mounts]]
    source = 'node_modules/@fontsource-variable/manrope/files'
    target = 'static/fonts'
    includeFiles = '*-latin-*'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
